"""add iv30 column

Revision ID: 988b2f0cbfff
Revises: fa92afa9a3de
Create Date: 2026-01-19 12:20:58.105432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988b2f0cbfff'
down_revision: Union[str, Sequence[str], None] = 'fa92afa9a3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screen_results', sa.Column('iv30', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screen_results', 'iv30')
    # ### end Alembic commands ###
