"""Initial tables

Revision ID: fa92afa9a3de
Revises: 
Create Date: 2026-01-18 21:58:20.778934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa92afa9a3de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=False)
    op.create_table('screen_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('p_fcf', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screen_results_date'), 'screen_results', ['date'], unique=False)
    op.create_index(op.f('ix_screen_results_id'), 'screen_results', ['id'], unique=False)
    op.create_index(op.f('ix_screen_results_score'), 'screen_results', ['score'], unique=False)
    op.create_index(op.f('ix_screen_results_symbol'), 'screen_results', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screen_results_symbol'), table_name='screen_results')
    op.drop_index(op.f('ix_screen_results_score'), table_name='screen_results')
    op.drop_index(op.f('ix_screen_results_id'), table_name='screen_results')
    op.drop_index(op.f('ix_screen_results_date'), table_name='screen_results')
    op.drop_table('screen_results')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
