"""Add sentiment table

Revision ID: fae2f7565355
Revises: 988b2f0cbfff
Create Date: 2026-01-19 13:04:38.841714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae2f7565355'
down_revision: Union[str, Sequence[str], None] = '988b2f0cbfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_sentiment',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('sentiment_source_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_stock_sentiment_symbol'), 'stock_sentiment', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_sentiment_symbol'), table_name='stock_sentiment')
    op.drop_table('stock_sentiment')
    # ### end Alembic commands ###
